### ISSUE TITLE
[Feature] ColorPicker

### ISSUE THREAD

**Issue by frechdax1337** [DarkByte7/VisualPlus#10]
Feature idea:
Example:
![2017-04-04_19-02-19](https://cloud.githubusercontent.com/assets/26886116/24680774/93519564-1992-11e7-9643-d8923337bb2b.png)

**Comment by DarkByte7** [comment]
The VisualColorWheel should be available now in the beta branch.
![VisualColorWheel](http://i.imgur.com/XKh5rB8.png)
