### ISSUE TITLE
Tabcontrol does not center text when changing ItemSize

### ISSUE THREAD

**Issue by frechdax1337** [DarkByte7/VisualPlus#12]
Example:
![2017-04-05_11-53-42](https://cloud.githubusercontent.com/assets/26886116/24700157/930dba10-19f6-11e7-9427-55dca5642081.gif)

&

The name change (VisualTab to VisualTabControl) broke my project, so i had to rename it.
(i dont know if im the only one but just wanted to give this information)

**Comment by DarkByte7** [comment]
The ItemSize is not setup for the default vertical tab yet properly. This will be added once #8 is done.
