### ISSUE TITLE
VisualCheckedListBox Control

### ISSUE THREAD

**Issue by frechdax1337** [DarkByte7/VisualPlus#16]
1. A checkedlistbox would be pretty nice to have. (could be a property of the listbox)
Example:
![2017-04-05_21-28-19](https://cloud.githubusercontent.com/assets/26886116/24723191/dc28b470-1a46-11e7-915b-2defcf47050b.gif)

**Comment by DarkByte7** [comment]
Made it into 2 separate issues.
#19 Add: Smart tags support.
