### ISSUE TITLE
Can't make visualRadioButton checked

### ISSUE THREAD

**Issue by aller70** [DarkByte7/VisualPlus#2]
Also, visualRadioButton + visualGroupBox -> visualRadioButton Background color is Black in DesignTime and RunTime
![image](https://cloud.githubusercontent.com/assets/13942911/24651021/d8ccc3e2-1934-11e7-88f3-4d088b6b19a7.png)

**Comment by DarkByte7** [comment]
The BackColor for the controls is a separate issue with the VisualGroupBox & VisualPanel containers.
The RadioButton should work now properly again.
