### ISSUE TITLE
VisualListbox item hover border remains.

### ISSUE THREAD

**Issue by frechdax1337** [DarkByte7/VisualPlus#20]
If you select multiple items they draw a line between each other:
![2017-04-06_12-01-04](https://cloud.githubusercontent.com/assets/26886116/24748691/c3ce4820-1ac0-11e7-829b-2482d207bf9d.gif)

**Comment by DarkByte7** [comment]
When the mouse leaves the control it `Invalidates()` on `MouseLeave`. Then it repaints it without the lines until you move over the item again.
