### ISSUE TITLE
[Feature] Dropdown Container

### ISSUE THREAD

**Issue by frechdax1337** [DarkByte7/VisualPlus#22]
It looks like a combobox but if it drops down, there is a container.
Ive got no examples since I never saw anything like that before.

**Comment by DarkByte7** [comment]
Is this what your asking for?
![Container](https://i.stack.imgur.com/6mY0M.png)

Being able to change the drop down style to something like this?
![DropDownStyle](http://www.jqueryscript.net/images/Browser-Context-Menu-Replacement-Plugin-With-jQuery-rClick-js.jpg)

**Comment by frechdax1337** [comment]
No like when you click the dropdown, a panel slides down where you can put any controls

**Comment by DarkByte7** [comment]
If you could find or make an example image it would help out identifying what it is you would like to see.

**Comment by frechdax1337** [comment]
![windowsformsapp7_2017-04-06_22-07-10](https://cloud.githubusercontent.com/assets/26886116/24773527/e4f3dbe6-1b15-11e7-8ea1-f30924f8b80f.png)

**Comment by DarkByte7** [comment]
Yeah I think that would be an advanced ContextMenu that you can just bind to your ComboBox.
![AdvancedContextMenu](https://www.codeproject.com/KB/menus/SuperContextMenu/Picture1_small.jpg)

**Comment by DarkByte7** [comment]
Migrated issue to: #25
