### ISSUE TITLE
[Bug] Not able to mark items in a GroupBox

### ISSUE THREAD

**Issue by frechdax1337** [DarkByte7/VisualPlus#24]
When you try to mark multiple items in a groupbox, it does not select the items, it moves the groupbox.
Example on a GroupBox:
![2017-04-06_17-58-45](https://cloud.githubusercontent.com/assets/26886116/24763794/b1faea04-1af2-11e7-8182-1eed4a50419f.gif)
Example on a Panel: (or how it should be)
![2017-04-06_18-00-30](https://cloud.githubusercontent.com/assets/26886116/24763871/f4eb21f8-1af2-11e7-8de3-45e7d46aabe6.gif)
Example on a dark Panel: (so you can see the box)
![2017-04-06_18-05-07](https://cloud.githubusercontent.com/assets/26886116/24764106/a33ce034-1af3-11e7-851e-9059afecc4ca.gif)

-------
VisualPlus version: 0.4.0.2

**Comment by DarkByte7** [comment]
Should be resolved with issue. #23
