### ISSUE TITLE
visualListView not paint Items in List mode, Detail mode on screenshot

### ISSUE THREAD

**Issue by aller70** [DarkByte7/VisualPlus#3]
![image](https://cloud.githubusercontent.com/assets/13942911/24650740/d6f533c0-1933-11e7-9bdb-defcf9302ca4.png)

**Comment by DarkByte7** [comment]
The VisualListView only supports Detail mode currently. Have you tried the VisualListBox?

**Comment by aller70** [comment]
Detail mode bug on screenshot. What is  VisualListBox? I can't find this control in VisualPlus.

**Comment by DarkByte7** [comment]
You can get the latest fresh builds here (Includes the latest fixes and controls that are being worked on): [Download](https://ci.appveyor.com/project/DarkByte7/VisualPlus/build/artifacts)
