### ISSUE TITLE
The references root node is not available

### ISSUE THREAD

**Issue by YuqseLx** [DarkByte7/VisualPlus#48]
When i want add or delete anything or resize any control it's giving this error. Sorry it's language Turkish.
![IMG](https://i.gyazo.com/c2935241227b20e25952adc2c7aee0d0.png)
Translated text :  Could not generate code for the 'Cursor' property. Error: "The references root node is not available."

**Comment by DarkByte7** [comment]
From my understanding having invalid or multiple references linked to your project can cause an error like this. Try removing and then adding the VisualPlus reference to your project.

Try opening a new project and adding a VisualButton there and resizing it.
