### ISSUE TITLE
ControlBox not showing on VisualForm.

### ISSUE THREAD

**Issue by PedroFGP** [DarkByte7/VisualPlus#50]
Not sure if a bug, but even if the ControlBox boolean in the form properties is True the ControlbBox control is not showing.

![bugvp](https://user-images.githubusercontent.com/32468820/35927100-ff413c86-0c10-11e8-86ec-dd0b0f1a26a9.png)
 
Adding it manualy works...

**Comment by DarkByte7** [comment]
The  `ControlBox ` on the  `VisualForm ` is set to  `FALSE ` by default. 

The disadvantage of using the default one was the lack of customization it offered. Use the  `VisualControlBox ` control it can be found in the  `ToolBox `.

**Comment by PedroFGP** [comment]
Thanks for the fast reply, btw thanks again for Visual Plus itself!

**Comment by DarkByte7** [comment]
Thank you for your feedback. I have implemented the  `VisualControlBox ` on the  `VisualForm ` as the default.
