### ISSUE TITLE
VisualForm magnetic property

### ISSUE THREAD

**Issue by PedroFGP** [DarkByte7/VisualPlus#51]
Whenever I run my application and drag and move a form a bit out of the "middle" of the screen it seems to snap to the top or bottom (to which it is closer). It seems something related to the drag of the form, the calculations might be a bit off.

PS: I should provide more details or even search it myself in the source but I'm really busy.

Thanks for your time!

**Comment by DarkByte7** [comment]
The ‘Magnetic’ property value for the ‘VisualForm’ is set to ‘true’ by default. Set it to ‘false’ to disable it. Or you can play around with the ‘MagneticRadius’ property.

Will make the minor adjustment when I get to a computer.

**Comment by PedroFGP** [comment]
Thanks one more time, sorry for being stupid 👍

**Comment by DarkByte7** [comment]
No such thing as stupid questions. The project is lacking some documentation, which I'm adding as I have time. If you got any further questions you can also just drop in for a <a href="https://gitter.im/VisualPlusUI/General"><img alt="Gitter" src="https://img.shields.io/gitter/room/nwjs/nw.js.svg"></a>.
