### ISSUE TITLE
VisualForm Text "cutting" last character

### ISSUE THREAD

**Issue by PedroFGP** [DarkByte7/VisualPlus#56]
Whenever I set the Text property form a Form to a certain text it "cuts" the last letter:

![issue](https://user-images.githubusercontent.com/32468820/37684029-5905f686-2c6d-11e8-868e-a7e8dc79963c.png)

PS: if I append another "o" at the end it seems to work: "Introduçãoo".

**Comment by DarkByte7** [comment]
The issue should be resolved now. Let me know if any further controls don't render their Text properly.
