### ISSUE TITLE
VisualListView - Leave selected item "drawn" when focus is lost

### ISSUE THREAD

**Issue by PedroFGP** [DarkByte7/VisualPlus#57]
When the focus is lost (VisualListView) the selected row is no longer drawn (ItemSelected color).

Is it possible to add an option to force this (bool)?

Thanks for your time,

Pedro.

**Comment by DarkByte7** [comment]
Try setting the `HideSelection` property to `False` on the `VisualListView`.

**Comment by PedroFGP** [comment]
Just did and it bugs out coloring every item as it is "selected"

![bug](https://user-images.githubusercontent.com/32468820/39652773-148fdf5a-4fc5-11e8-9945-17bb1b45f157.png)

**Comment by DarkByte7** [comment]
How are you changing the focus of the control using a keyboard, mouse or both when it does that?

**Comment by PedroFGP** [comment]
Clicking on another control (mouse)
