### ISSUE TITLE
VisualForm - No Title Buttons

### ISSUE THREAD

**Issue by furesoft** [DarkByte7/VisualPlus#59]
hi, how can i enable the title buttons - minimize and close?

all props for that are true

**Comment by furesoft** [comment]
this.ControlBox.MinimizeButton.Enabled = true;
doesnt work ControlBox is a boolean

**Comment by furesoft** [comment]
and all set to true but no controlbox is visible

**Comment by DarkByte7** [comment]
The reason `ControlBox` is a `bool` is cause your using a `Form` and not the `VisualForm`.

Please read: https://github.com/DarkByte7/VisualPlus/wiki/Quick-Start#to-create-a-simple-visualplus-application-using-a-visualform

**Comment by furesoft** [comment]
no its visualform
`public partial class Form1 : VisualForm
    {
        public Form1()
        {
            InitializeComponent();
        }

        private void Form1_Load(object sender, System.EventArgs e)
        {
            stylesManager1.AddFormToManage(this);
            this.MinimizeBox = true;

            // Turn on usability.
            this.ControlBox = true;
            stylesManager1.Update();
        }
    }`

**Comment by DarkByte7** [comment]
I have created a unit test that does pretty much what your asking. I would recommend you check it out its called `VisualFormTest`. Give the test a run to see it in action, all the code is provided. 8f18e0c3bc3bc93759f3fe157fd8fe84f1b4a6bc

Which version are you using? I'm wondering if your maybe using an older version. Check your `References` in your project under `Solution Explorer`. You can download the latest builds here: [Fresh Build Artifacts](https://ci.appveyor.com/project/DarkByte7/VisualPlus/build/artifacts)

**Comment by furesoft** [comment]
im using the latest nuget version

**Comment by DarkByte7** [comment]
That's strange since I'm also using that version for another project via nuget and it works as intended. Make sure it's `v0.4.1.4` that you have referenced in your project. You can also send me your project or a compilable sample of it then I can diagnose the issue better.

**Comment by furesoft** [comment]
its only the 0.4.1.2 available to install

**Comment by DarkByte7** [comment]
Your 2 versions behind.

Downloads `v0.4.1.4`:
[GitHub Releases](https://github.com/DarkByte7/VisualPlus/releases/tag/v0.4.1.4)
[Nuget](https://www.nuget.org/packages/VisualPlus/0.4.1.4-beta)
