### ISSUE TITLE
VisualDateTimePicker

### ISSUE THREAD

**Issue by n3R0d0T** [DarkByte7/VisualPlus#65]
Do you have future plans in including the datetimepicker in this framework? Thanks.

**Comment by DarkByte7** [comment]
Yes, I would like to eventually as time allows. Just hasn't been asked for yet so it hasn't been a priority. Once I have completed the project im currently working on. Got a bit of bug fixing and documentation I need to catch up on as well. Then I will shift my focus towards that control then.

If you know how to get started feel free to open a pull request then I could help work on it together and start implementing it into the framework.
