### ISSUE TITLE
set VisualButton as a form's AcceptButton

### ISSUE THREAD

**Issue by mimirobo** [DarkByte7/VisualPlus#69]
I couldn't find any ways to set _VisualPlus.Toolkit.Controls.Interactivity.VisualButton_ as _System.Windows.Forms.Form_'s AcceptButton.

I guess the **VisualButton** class should inherits **IButtonControl** Interface.

**Comment by DarkByte7** [comment]
Thank you for reporting the issue. It should be fixed now.

**Comment by mimirobo** [comment]
Anytime
