### ISSUE TITLE
VisualForm unable to scale

### ISSUE THREAD

**Issue by masterheroit** [DarkByte7/VisualPlus#71]
[![Screenshot from Gyazo](https://gyazo.com/87e6d0c6663f4d9ac46cf2fb042189f1/raw)](https://gyazo.com/87e6d0c6663f4d9ac46cf2fb042189f1)
[![Screenshot from Gyazo](https://gyazo.com/011e46d0a82679c0693ae0571b42b49b/raw)](https://gyazo.com/011e46d0a82679c0693ae0571b42b49b)

**Comment by DarkByte7** [comment]
Can you fill this out?

**To Reproduce**
Steps to reproduce the behavior:
1. Go to '...'
2. Click on '....'
3. Scroll down to '....'
4. See error

**VisualPlus (please complete the following information):**
 - Version [e.g. v0.4.0.1]

**Additional context**
Add any other context about the problem here.

**Comment by masterheroit** [comment]
Founded on : Just create the form .
VisualPlus Version : Version 0.4.1.5-beta-HotFix1
some of the custom form i found on internet got this scale error too . but most of them are scaling properly

**Comment by masterheroit** [comment]
Sorry the late respond

**Comment by masterheroit** [comment]
I  installed and apply this dll through nuget

**Comment by masterheroit** [comment]
Update : Nows the control are misplace . 
https://openload.co/f/l8Ugy7LCYbs/Desktop_2018.08.16_-_19.45.17.01.mp4

However , the dll that i got same error like this before its now working properly

**Comment by DarkByte7** [comment]
Glad to hear it is now working as intended. 

Without proper and clear explanation what your intentions are or code to show it. Im gonna take a leap of faith. 

By controls I’m assuming your referring to the VisualControlBox being out of place? Just update your X coordinate with the Visual Studio designer on the properties panel for the VisualForm. Then try resizing the form, it should remain anchored.

Dynamic Code (Example):
`this.ControlBox.Location = new Location(123, this.ControlBox.Y);`
