### ISSUE TITLE
Files(s) Might Affected With Trojan:JS/CoinHive.B

### ISSUE THREAD

**Issue by masterheroit** [DarkByte7/VisualPlus#74]
**To Reproduce**:
1. Go to VisualPlus-master\docs\index.html
2. Get a notification from antivirus

Heres Virustotal Result
https://www.virustotal.com/#/file-analysis/YTMxNjM2ZTNhZTQ2MTNmOWUwOTdmOTc3MmViOWY1Mzc6MTU0NjY3MjQyNQ==

**Environment (please complete the following information)**:
commit 35a266c
windows 10
google chrome
windows defender

**Comment by DarkByte7** [comment]
Can confirm that is not a virus. And rather a miner to help support development. If you don’t want to support it thru the method you can simply block the script in an AdBlocker.
