### ISSUE TITLE
[Feature] Trackbar value on button/hide button

### ISSUE THREAD

**Issue by frechdax1337** [DarkByte7/VisualPlus#9]
Ideas for the Trackbar:
Trackbar button value:
Examples:
![opera_2017-04-04_23-48-13](https://cloud.githubusercontent.com/assets/26886116/24680469/52d325d0-1991-11e7-960e-e883f21b3c9e.png)
without button:
![opera_2017-04-04_23-50-21](https://cloud.githubusercontent.com/assets/26886116/24680651/0a3d784c-1992-11e7-8c7d-78c73d30c82c.png)

Hide button:
Hide the button, so you can just see the line (looks more modern IMO) (saves space vertically)

**Comment by DarkByte7** [comment]
When you don't have a button for the Trackbar then wouldn't that be more of a ProgressBar?
